spring:
   application:
      name: spring-cloud-eureka-client
   datasource:
      url: jdbc:mysql://127.0.01:3306/allmarket
      username: root
      passowrd: null
server:
   port: 0
eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
   instance:
      preferIpAddress: true